projet_darties_AMOA:
  outputs:
    dev:
      dataset: darties_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:/Users/alexa/keys/bq-creds.json
      location: EU
      method: service-account
      priority: interactive
      project: '872484084279'
      threads: 4
      type: bigquery
  target: dev
